# Generated by Django 4.2.5 on 2023-09-21 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KabupatenKota',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('kabupatenKota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kunciapp.kabupatenkota')),
            ],
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kelurahan',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kunciapp.kecamatan')),
            ],
        ),
        migrations.AddField(
            model_name='kabupatenkota',
            name='provinsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kunciapp.provinsi'),
        ),
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('jenis_kelamin', models.IntegerField(choices=[(0, 'Tidak memilih'), (1, 'Laki-laki'), (2, 'Perempuan')], default=0)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tgl_lahir', models.DateField()),
                ('no_telp', models.CharField(max_length=20)),
                ('kabupaten_kota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kunciapp.kabupatenkota')),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kunciapp.kecamatan')),
                ('kelurahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kunciapp.kelurahan')),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kunciapp.provinsi')),
            ],
        ),
    ]
